import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'firebase_options.dart';
import 'app.dart';
import 'injection_container.dart';
// Generated by `flutterfire configure`. See README → Firebase setup.
// import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialise Firebase. After running `flutterfire configure`, switch to:
  //   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  // Register all services, repositories and BLoCs.
  await configureDependencies();

  runApp(const FeedbackApp());
}
